language: ruby
rvm:
- 1.9.3
- 2.0.0
before_install:
- git submodule foreach --recursive git submodule sync
- git submodule update --init --recursive
matrix:
  allow_failures:
env:
  global:
before_script: mysql -e 'create database ccng;'
after_failure: bin/after_failure.sh
